// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukdkouzhgylltslkxzhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZGtvdXpoZ3lsbHRzbGt4emh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTg5MTEsImV4cCI6MjA2NTU3NDkxMX0.arry4j7HMfgaqBxAYjx1fn8Gpny06IBK9brZapvwALA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);